### PR TITLE
[SET-494] eap-7.4.x-jdk17-testsuite job has wrong parameters defined

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/SET-494

this PR depends on https://github.com/jboss-set/hera/pull/14

### CODE REVIEW

**Review by rpelisse — APPROVED** [review]
@spyrkob LGTM!

**Comment by gaol** [comment]
> @gaol looks good, but we need to also compile with -Delytron right?

Yes, it has the `-Delytron -DnoCompile` specified

**Comment by gaol** [comment]
Please on hod.

* `TESTSUITE_OPTS=-Delytron -DnoCompile` would cause `hera/job.sh` fail because there is a space in between
* `CGROUP_MOUNT_ENABLED` as booleanParam makes it always has value even unset, like: `CGROUP_MOUNT_ENABLED="false"`, which fails the test of `[ -n "${CGROUP_MOUNT_ENABLED}" ];`

I will work on it and push later.

**Comment by gaol** [comment]
Please on hod.

* `TESTSUITE_OPTS=-Delytron -DnoCompile` would cause `hera/job.sh` fail because there is a space in between
* `CGROUP_MOUNT_ENABLED` as booleanParam makes it always has value even unset, like: `CGROUP_MOUNT_ENABLED="false"`, which fails the test of `[ -n "${CGROUP_MOUNT_ENABLED}" ];`

I will work on it and push later.

**Comment by spyrkob** [comment]
Is `CGROUP_MOUNT_ENABLED` something we need because of Java 17? Do we need it in every job running on 17?

**Comment by gaol** [comment]
> Is `CGROUP_MOUNT_ENABLED` something we need because of Java 17?

yes, it is.

> Do we need it in every job running on 17?

I think currently only `eap-7.4.x-jdk17-testsuite` job using JDK 17, but yes, I think so before https://bugs.openjdk.java.net/browse/JDK-8286212 gets fixed

**Comment by spyrkob** [comment]
I'm wondering if we can add it automatically in either the builder or one of Util classes whenever job uses JDK17. Just to avoid gotchas and repetition when we have more jobs on 17

**Comment by rpelisse** [comment]
So, generally speaking, I don't think jobs should be tweaking what is added as volume to the container. The fact that we have to add cgroup is a nasty workaround. So I would rather avoid building changes around this specific requirements. Hopefully, it will be fixed soon and we'll be able to remove this entirely.

**Comment by gaol** [comment]
Updated to add additional job: `eap-7.4.x-jdk17-build`, which will build on JDK8 with options: `-Delytron -DallTests -DskipTests` which builds all test modules as well, then the job `eap-7.4.x-jdk17-testsuite` will copy bits from `eap-7.4.x-jdk17-build` and run with options: `-Delytron -DnoCompile -DallTests` on JDK 17.

**Comment by gaol** [comment]
This PR is ready to get merged if nobody object :)

**Pull request merged**
