### PR TITLE
remove ci job for deprecated assistant repository

### PR DESCRIPTION
**Pull request by soul2zimate**
remove ci job for deprecated assistant repository https://github.com/jboss-set/assistant

### CODE REVIEW

**Comment by rpelisse** [comment]
@spyrkob any reason to push back on this?

@soul2zimate Can you remove the job from Jenkins (using the WebUI). Running Cedalion will not clean that up for us.

**Review by rpelisse — APPROVED** [review]
LGTM

**Review by spyrkob — APPROVED** [review]
LGTM 

+1 to removing stuff 😂

**Comment by rpelisse** [comment]
@soul2zimate Do we keep the assistant-ci job? Or can this go too?

**Comment by soul2zimate** [comment]
> @soul2zimate Can you remove the job from Jenkins (using the WebUI). Running Cedalion will not clean that up for us.

sure, I have removed the `assistant-ci` job in Olympus

**Pull request merged**
