### PR TITLE
SET-469 Move component-alignment-config-template.csv.j2 to Cedalion

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/SET-469

### CODE REVIEW

**Comment by rpelisse** [comment]
@spyrkob LGTM but I certainly defer to your expertise here! Let me know if we can merge this :)

**Review by rpelisse — APPROVED** [review]

**Comment by spyrkob** [comment]
Is there a harmonia PR to use the new properties instead of the template?

**Comment by RanabirChakraborty** [comment]
I have used the templates and modified that inside `jobs/component-aligment.groovy`. About the Zeus part, the plan was to move the templates from there.

**Comment by spyrkob** [comment]
Without changes in harmonia the new properties are not going to be picked up. See https://github.com/jboss-set/harmonia/blob/olympus/upgrade-components-report.sh#L90-L107.

**Review by spyrkob — APPROVED** [review]
LGTM

**Review by spyrkob — APPROVED** [review]
Hera PR: https://github.com/jboss-set/hera/pull/12

**Review by rpelisse — APPROVED** [review]

**Pull request merged**
