### PR TITLE
[SET-447] fix path of eap-job.sh to eap-job/olympus.sh for cryo jobs

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/SET-447

### CODE REVIEW

**Comment by gaol** [comment]
@rpelisse @spyrkob would you please review ? thanks

**Review by spyrkob — APPROVED** [review]
LGTM

**Comment by rpelisse** [comment]
@gaol LGTM too! Please merge and run the job-configurator to update the jobs whenever you have the time!

**Review by rpelisse — APPROVED** [review]

**Comment by gaol** [comment]
thanks guys, but I don't have permission to merge PRs of this repository, same for https://github.com/jboss-set/harmonia/pull/73 :)

**Comment by rpelisse** [comment]
@gaol merged!

**Pull request merged**
